# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: jang suyeong
title: 풀스택 개발자입니다.
email: suyeong1020@naver.com
website: https://www.notion.so/JAVA-SPRING-3fd9bee1a6934392bed6b1351a64a35b

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: jangsuyeongg
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs











  I am most skilled in: - 데이터에 관심이 많아 데이터를 관리하고 활용하는 것을 좋아하는 예비 개발자입니다.
- `새로운 것을 학습하고 성장하는 개발 문화에 흥미를 느껴` 개발을 시작하게 되었습니다.
- java와 database 공부를 습관화하며, `초심을 잃지 않는 개발자`가 되고 싶습니다.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Leaf Coffee Project
        link: github.com/jangsuyeongg/Project
        # link_text: Project Website
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Coffee Franchise Management Web Service
        description: | # this will include new lines to allow paragraphs
          <mark>Spring MVC</mark>를 기본기술로 활용한 웹 페이지 제작
          DB연결은<mark>Mybatis</mark>로 <mark>ORACLE Database</mark>를 연결
          <mark> HTML5</mark> 와 <mark> CSS3</mark> 를 사용하여 UI 를 구성하였고, <mark>JavaScript</mark>와 <mark>JQUERY</mark>를 주로 사용하여 이벤트 처리
          비동기 데이터 처리방식인<mark>  Ajax</mark>를 통하여 페이지를 구성하여 자바 컨트롤러와 통신을 통해 URL과 값 전달

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: bitcamp
        caption: 2021.0517 ~ 2021.1029
        sub_title: 디지털컨버전스 기반 융합기술을 활용한 SW웹 개발자 양성과정C (Java/Spring 풀스택 개발자 과정)
        quote: >

        description: | # this will include new lines to allow paragraphs
          JAVA
            - Implement, Abstract, Interface, Collection, I/O, Thread, Network, JDBC

          Oracle Database
            - DML, DDL, Group by, SubQuery, DBMS Grant

          Front-end
            - HTML5, CSS, CSS3, JavaScript, JQuery, Ajax

          JSP & Servlet, 
            - Action tag, cookie, Session, Exception, 
            - DBCP, EL, JSTL,
            - MVC, FrontController, Command Pattern, Forwading

          Spring 
            - DI, Bean LifeCircle, AOP
            - Controller, RequestMapping, 
            - Mybatis, Bootstrap
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
